### ISSUE TITLE
Express server reporting deprecated value

### ISSUE THREAD

**Issue by tightrough** [petrarchy/arctype#24]
`express-session deprecated undefined saveUninitialized option; provide saveUninitialized option server/index.js:66:38`

Turns out line 38 was missing an i in `saveUninitialized`. Also, line 41 seems like it might have picked up an extra i in `graphql: true` - please confirm.

**Comment by dennismphil** [comment]
Commit #17 was the fix for express session warning.

graphiql seems correct as per the documentation https://github.com/graphql/express-graphql
